// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// import type { Metadata } from "next";
import { Montserrat, Nunito } from "next/font/google";
import "./globals.css";
import Header from "../components/header.js";
import Footer from "../components/footer.js";

const montserrat = Montserrat({ subsets: ["cyrillic", "latin"], variable: "--font-sans" });
const playfair = Nunito({ subsets: ["cyrillic", "latin"], variable: "--font-serif" });
// const playfair = Playfair_Display({ subsets: ["cyrillic", "latin"], variable: "--font-serif" });


// export const metadata: Metadata = {
//   title: "ООО Докмед | Врач общей практики",
//   description: "Доказательная медицина, индивидуальный подход и забота о вашем здоровье.",
// };
export const metadata = {
  title: "ООО Докмед | Врач общей практики",
  description: "Индивидуальный подход и забота о вашем здоровье.",
};

export default function RootLayout({ children, }) {
  return (
    <html lang="ru" className="scroll-smooth">
      <body className={`${montserrat.variable} ${playfair.variable} font-sans flex flex-col min-h-screen relative`}>
        <Header />
        <main className="flex-grow pt-24">{children}</main>
        <Footer />
      </body>
    </html>
  );
}